# Generated by Django 3.0.4 on 2020-07-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.IntegerField(max_length=60)),
                ('numberofpeople', models.IntegerField(max_length=60)),
                ('timerange', models.DateTimeField(max_length=60)),
            ],
        ),
    ]
