# Generated by Django 3.0.4 on 2020-07-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomApp', '0002_auto_20200705_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='numberofpeople',
            new_name='max_numberofpeople',
        ),
        migrations.RemoveField(
            model_name='room',
            name='timerange',
        ),
    ]
