# Generated by Django 3.0.4 on 2020-07-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomApp', '0004_bookingdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromTime', models.DateTimeField()),
                ('toTime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='BookingData',
        ),
    ]
