# Generated by Django 3.0.4 on 2020-07-05 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoomApp', '0005_auto_20200705_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervaldata',
            name='roomidstored',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roompickup', to='RoomApp.Room'),
        ),
    ]
