# Generated by Django 3.0.4 on 2020-07-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomApp', '0009_room_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='booked',
        ),
        migrations.RemoveField(
            model_name='room',
            name='capacityOfRoom',
        ),
    ]
